version: '3.8'
services:
  iris:
    image: intersystemsdc/iris-community:latest
    environment:
      IRIS_USERNAME: demo
      IRIS_PASSWORD: demo
    restart: always
    hostname: iris
    ports:
      - 1972:1972
      - 52773:52773
    networks:
      - sameNetwork


  flask_server:
    build: .
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=iris 
      - DATABASE_PORT=1972
    hostname: flask_server
    ports:
      - "5010:5010"
    depends_on:
      - iris 
    networks:
      - sameNetwork

networks:
  sameNetwork:
